<h3>Nombre:</h3>
<h5>{{$mensaje['nombre']}}</h5>
<br>
<h3>Email:</h3>
<h5>{{$mensaje['email']}}</h5>
<br>
<h3>Telefono:</h3>
<h5>{{$mensaje['telefono']}}</h5>
<br>
<h3>Mensaje:</h3>
<h5>{{$mensaje['mensaje']}}</h5>